# Generated by Django 3.2.5 on 2021-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заказы')),
                ('clients_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('clients_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('clients_car', models.CharField(max_length=50, verbose_name='Автомобиль')),
                ('services', models.CharField(max_length=50, verbose_name='Услуги')),
                ('employees', models.CharField(max_length=50, verbose_name='Сотрудники')),
                ('orders', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
