# Generated by Django 3.2.6 on 2021-08-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка Авто')),
            ],
            options={
                'verbose_name': 'Марка Авто',
                'verbose_name_plural': 'Марки Авто',
                'ordering': ['brand'],
            },
        ),
    ]
